server:
#服务器端口
    port: 8099

spring:
    #配置数据源
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.4.179.240:3306/mylouise?serverTimezone=GMT%2B8
#        url: jdbc:mysql://127.0.0.1:3306/mylouise?serverTimezone=GMT%2B8
        username: root
        password: RMTouHou.18
#        password: root
    #静态资源路径
    mvc:
        static-path-pattern: /static/**


#配饰mybatisPlus
mybatis-plus:
    configuration:
        #关闭表字段下划线自动转驼峰导致实体类字段无法匹配
        map-underscore-to-camel-case: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:xml
    global-config:
        db-config:
            #表名前缀
            table-prefix: t_

#Louise相关配置
LOUISE:
    HELP_PAGE: https://chenjie.ink:8096/file/images/Image_20210814200900036_WUuK.jpg
    ADMIN_NUMBER: 412543224
    #图片缓存位置
    CACHE:
        IMAGE_LOCATION: cache/images/
    #报错信息
    ERROR:
        UNKNOWN_COMMAND: 露易丝没有听懂诶，如果需要帮助的话请说!help
        THIRD_API_REQUEST_FAILED: 露易丝请求失败了！
        UNKNOWN_USER: 你还没有在露易丝这里留下你的记录哦，请使用!join
        BANNED_USER: 你的权限暂时被禁用了哦
        UPLOAD_IMAGE_FAILED: 上传图片失败！请检查你的参数是否正确，以这种格式使用哦!find [图片]
#CQ-HTTP相关配置
BOT:
    LOUISE_CACHE_IMAGE: ../../../../MyLouise/cache/images/
    BASE_URL: http://127.0.0.1:5700
    HTTP_POST_KEY: Ac0mq5WxAVVIMAyj8Dx0TYKXjwNiKlbn
#第三方API相关配置
API:
    PIXIV:
        REVERSE_PROXY: https://i.pixiv.re/
        PROXY_URL: https://pixiv.re/
    SOURCENAO:
        URL: https://saucenao.com/search.php
        API_KEY: 1b1b6103a6503e94cc5dcef861f041aadd72ec49
        ERROR:
            REQUEST_FAILED: SourceNAO出问题了，不关咱的事
