server:
#服务器端口
    port: 8099

spring:
    #配置数据源
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.4.179.240:3306/mylouise?serverTimezone=GMT%2B8
        username: root
        password: RMTouHou.18

#配饰mybatisPlus
mybatis-plus:
    configuration:
        #关闭表字段下划线自动转驼峰导致实体类字段无法匹配
        map-underscore-to-camel-case: false
    mapper-locations: classpath*:xml
    global-config:
        db-config:
            #表名前缀
            table-prefix: t_